### PR TITLE
fix: allow to select non indexed profile

### PR DESCRIPTION
**Pull request by dzbo**
### Ticket ID

[DEV-11529](https://app.clickup.com/t/2645698/DEV-11529)

### Description

We should allow to paste valid addresses even if they are not indexed yet. They will appear and behave like entering EoA.

### CODE REVIEW

**Comment by Hugoo** [comment]
Task linked: [DEV-11529 Make sure we don't block user from sending LYX or asset to an address](https://app.clickup.com/t/2645698/DEV-11529)

**Review by JeneaVranceanu — CHANGES_REQUESTED** [review]
It "caches" last address that was used before the current input.
I've entered `0x0000000000000000000000000000000000000000`, send button got enabled, then I entered just random characters and got this:

https://github.com/user-attachments/assets/4468e1c5-00f3-4a3f-a020-69d560fdc85d

**Comment by JeneaVranceanu** [comment]
> It "caches" last address that was used before the current input. I've entered `0x0000000000000000000000000000000000000000`, send button got enabled, then I entered just random characters and got this:
> 
>  bug.mov

Maybe that's expected until I select the next successful search result?

**Comment by dzbo** [comment]
> > It "caches" last address that was used before the current input. I've entered `0x0000000000000000000000000000000000000000`, send button got enabled, then I entered just random characters and got this:
> > bug.mov
> 
> Maybe that's expected until I select the next successful search result?

Atm if you don't select new profile then it will use previous one that is "currently selected". We could clear previous selection when user type new profile, thoughts @franckwei ?

**Comment by JeneaVranceanu** [comment]
I'd say the strange parts are: 
- I was able to click barely visible button;
- address gets selected when I do not select it. Though, it appears to be a feature available for a while. See video below.


https://github.com/user-attachments/assets/efdf57b3-811a-4364-a95e-8e75e69814b7


Maybe if the input is a valid address and there's no response from the indexer we show this valid address in the dropdown list? Not sure about complexity of implementing that yet.

**Comment by franckwei** [comment]
> > > It "caches" last address that was used before the current input. I've entered `0x0000000000000000000000000000000000000000`, send button got enabled, then I entered just random characters and got this:
> > > bug.mov
> > 
> > 
> > Maybe that's expected until I select the next successful search result?
> 
> Atm if you don't select new profile then it will use previous one that is "currently selected". We could clear previous selection when user type new profile, thoughts @franckwei ?

Yes let's clear previous selection when user starts typing new profile address, I don't think it should be break anything else, no?

**Comment by JeneaVranceanu** [comment]
> Yes let's clear previous selection when user starts typing new profile address, I don't think it should be break anything else, no?

I do not think it will break anything. The only "downside" is that user will have to type again to get previously selected address/profile if they need to and I feel it will not create any major inconvenience.

**Review by doubleppereira — APPROVED** [review]
LGTM

**Review by JeneaVranceanu — APPROVED** [review]

**Pull request merged**
