### PR TITLE
fix: Wallet Connect improvements

### PR DESCRIPTION
**Pull request by dzbo**
### Ticket ID

[DEV-12038](https://app.clickup.com/t/2645698/DEV-12038)
[DEV-12036](https://app.clickup.com/t/2645698/DEV-12036)
[DEV-12034](https://app.clickup.com/t/2645698/DEV-12034)
[DEV-11969](https://app.clickup.com/t/2645698/DEV-11969)

### Description

- remove redirect url from QR code (no extra redirect when scanning)
- fix issue with multiple QR code being generated

### CODE REVIEW

**Comment by Hugoo** [comment]
Task linked: [DEV-12036 Bug: duplicate QR code](https://app.clickup.com/t/2645698/DEV-12036)

**Comment by Hugoo** [comment]
Task linked: [DEV-12038 Bug: redirectUrl sent through walletconnect is not correct (also remove redirectUrl from QR code to be scanned)](https://app.clickup.com/t/2645698/DEV-12038)

**Comment by Hugoo** [comment]
Task linked: [DEV-11977 Bug: QR code for mobile app doesn't work](https://app.clickup.com/t/2645698/DEV-11977)

**Review by JeneaVranceanu — APPROVED** [review]

**Comment by Hugoo** [comment]
Task linked: [DEV-11969 Deep link followers on mobile](https://app.clickup.com/t/2645698/DEV-11969)

**Pull request merged**
